### ISSUE TITLE
onduidelijk voor gebruiker 

### ISSUE THREAD

**Issue by Marwaxhello** [r20222/fix-the-flow-interactive-website#10]
De knop "zoek op allergeen" functie was niet duidelijk voor mij, misschien daarnaast een kleine text zetten met een soort van uitleg.

**Comment by r20222** [comment]
Ik heb er een text bijgezet. Ik hoop dat het zo iets duidelijker is.
![image](https://user-images.githubusercontent.com/101579892/208995941-e53efefc-ce0e-4f0a-9a34-12bf2ad4634b.png)
