### ISSUE TITLE
Wit ruimte

### ISSUE THREAD

**Issue by Marwaxhello** [r20222/fix-the-flow-interactive-website#11]
onder de knopjes heb je een grote gele stuk, misschien daar een plaatje plaatsen zodat je de aandacht van de gebruiker kan pakken. voor de rest heel mooi gedaan!

**Comment by r20222** [comment]
Dankjewel @Marwaxhello! Ik heb nu dat hele gele stuk weggelaten omdat het gele stuk eigenlijk onnodig was. Nu ziet het er zo uit: 
![image](https://user-images.githubusercontent.com/101579892/208996550-0d838b2c-4bf3-46ca-884c-4399dd2e46be.png)
